version: "3.8"
services:
  app:
    container_name: be-java-cafe-max
    image: yhkim951107/be-java-cafe-max:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - cafe_app:/app
    env_file:
      - datasource.env
  db:
    container_name: be-java-cafe-max-mysql-db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - ./db/mysql/initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - datasource.env
volumes:
  cafe_app:
