version: "3"
services:
  app:
    # container_name: spring-app
    image: yhkim951107/be-java-cafe-max
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: be_java_cafe_max
