version: "3.8"
services:
  app:
    container_name: be-java-cafe-max
    image: yhkim951107/be-java-cafe-max:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - cafe_app:/app
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/be_java_cafe_max?useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.username: root
      spring.datasource.password: yonghwan1107
      myName: yonghwan
  db:
    container_name: be-java-cafe-max-mysql-db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: yonghwan1107
      MYSQL_DATABASE: be_java_cafe_max
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - ./db/mysql/initdb.d:/docker-entrypoint-initdb.d
volumes:
  cafe_app:
