version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8000-8999:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: be_java_cafe_max
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
